### ISSUE TITLE
rfc2629toXHTML.xslt missing

### ISSUE THREAD

**Issue by hildjj** [reschke/xml2rfc#11]
Section 9.2 calls out rfc2629toXHTML.xslt for converting to XHTML.  I think the following is currently correct:

```
xsltproc rfc2629.xslt rfc2629xslt.xml -o rfc2629xslt.html
xsltproc --html HTMLtoXHTML.xslt rfc2629xslt.html -o rfc2629xslt.xhtml
prince rfc2629xslt.xhtml
```

**Comment by hildjj** [comment]
or skip the second step, and use `prince -i html *.html`

**Comment by reschke** [comment]
HTMLtoXHTML.xslt actually converts XSLTs, so it's used to transform rfc2629.xslt -> rfc2629toXHTML.xslt (which is not under source control as it's auto-generated).

I'll update the Prince-related section so it uses HTML directly.

**Comment by reschke** [comment]
https://github.com/reschke/xml2rfc/commit/bb5cd4771bc3d9d2b1f2332e8a68f090b95e7263
