### ISSUE TITLE
broken eref formatting

### ISSUE THREAD

**Issue by dret** [reschke/xml2rfc#12]
i am not sure this is the right "xml2rfc", but maybe? i am using xml2rfc online, and https://github.com/dret/I-D/blob/master/updating-rfcs/draft-wilde-updating-rfcs-00.xml#L23 used to work to create links. as noted in https://github.com/dret/I-D/issues/37, it no longer works and now seems to create completely wrong references.

**Comment by reschke** [comment]
No, this isn't the code that breaks for you. You need to report the problem at https://trac.tools.ietf.org/tools/xml2rfc/trac/report

**Comment by dret** [comment]
On 2016-09-15 01:47, Julian Reschke wrote:

> No, this isn't the code that breaks for you. You need to report the
> problem at https://trac.tools.ietf.org/tools/xml2rfc/trac/report

i think that's the write-only issue tracker that i now remember. i may 
even have reported a related bug a while ago, but i think nothing ever 
happened. anyway, thanks for the pointer!
