### ISSUE TITLE
clean-for-DTD.xslt creates a warning in rfc2629.xslt

### ISSUE THREAD

**Issue by martinthomson** [reschke/xml2rfc#13]
> INFO: No need to include 'Working Group' or 'Research Group' postfix in /rfc/front/workgroup value 'QUIC Working Group' (at line 32)

You should probably either remove the warning or the corresponding cleanup.

**Comment by reschke** [comment]
You mean clean up the source in the QUIC drafts? Will do.

**Comment by martinthomson** [comment]
I think that you misunderstood.  The QUIC drafts are messed up, but that's not the issue.

Check out that warning.  It is caused by clean-for-DTD mutating the `<workgroup>` element in a way that rfc2629 objects to.

**Comment by martinthomson** [comment]
It appears that you do the same cleanup twice.  You add "Working Group" or "Research Group" in both xslt files.  I would remove it from the former.  I don't see anything in the [preptool RFC](https://tools.ietf.org/html/rfc7998) regarding this, so you would be compliant.

**Comment by reschke** [comment]
But why do you run clean-for-DTD.xslt's output through rfc2629.xslt in the first place?

**Comment by martinthomson** [comment]
I don't know. It's your code (it's a revision of your pull request on the i-d-template code).  I assumed that you had a reason for doing it.

**Comment by reschke** [comment]
Please be more specific. Are we discussing https://github.com/reschke/i-d-template/blob/master/main.mk ?

**Comment by martinthomson** [comment]
Sure, when I use that, this warning is what results.  Is it invalid to clean then build?

**Comment by reschke** [comment]
Still don't understand. Look at 

  https://github.com/reschke/i-d-template/blob/master/main.mk#L56

that uses %.xml, not %.cleanxml.

**Comment by martinthomson** [comment]
OK, so I have an error in my usage.  I see.
