### ISSUE TITLE
Table of figures is outside nav.rfc\.toc

### ISSUE THREAD

**Issue by martinthomson** [reschke/xml2rfc#17]
I think that this is a simple error.

See the mess with http://httpwg.org/http-extensions/draft-ietf-httpbis-expect-ct.html

**Comment by reschke** [comment]
Yup - will fix.

**Comment by reschke** [comment]
Fixed in https://github.com/reschke/xml2rfc/commit/99c2f2db730ebd6cebd04e27d4926927dced765f
