### ISSUE TITLE
hook for CSS customization

### ISSUE THREAD

**Issue by reschke** [reschke/xml2rfc#2]
This should address the following use cases:

a) optionally prefix all CSS class names with something so that there'll be no name clashes

b) remap certain CSS class names to something else in order to harmonize with other code (such as site frameworks)

**Comment by mnot** [comment]
The specific hooks I need for (b) are control over the names of the classes that are currently:
- noprint
- error
- tt
- header

**Comment by reschke** [comment]
Please open new issues once new overrides are needed.
